Kitex:
  Service: "tags_service"
  Address: "0.0.0.0:8888"
  LogLevel: info
  LogFileName: "log/kitex.log"
  LogMaxSize: 10
  LogMaxAge: 3
  LogMaxBackups: 50

Registry:
  registry_address:
  - 127.0.0.1:2379
  username: ""
  password: ""

PostgresSQL:
  host: 127.0.0.1
  user: postgres
  password: postgres
  dbname: postgres
  port: 5432
  sslmode: disable

