// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: idl/likes.proto

package likes_service

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddLikesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Pid uint64 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *AddLikesRequest) Reset() {
	*x = AddLikesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_likes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLikesRequest) ProtoMessage() {}

func (x *AddLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_likes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLikesRequest.ProtoReflect.Descriptor instead.
func (*AddLikesRequest) Descriptor() ([]byte, []int) {
	return file_idl_likes_proto_rawDescGZIP(), []int{0}
}

func (x *AddLikesRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AddLikesRequest) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type AddLikesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AddLikesResponse) Reset() {
	*x = AddLikesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_likes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLikesResponse) ProtoMessage() {}

func (x *AddLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_likes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLikesResponse.ProtoReflect.Descriptor instead.
func (*AddLikesResponse) Descriptor() ([]byte, []int) {
	return file_idl_likes_proto_rawDescGZIP(), []int{1}
}

func (x *AddLikesResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddLikesResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DelLikesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Pid uint64 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *DelLikesRequest) Reset() {
	*x = DelLikesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_likes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelLikesRequest) ProtoMessage() {}

func (x *DelLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_likes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelLikesRequest.ProtoReflect.Descriptor instead.
func (*DelLikesRequest) Descriptor() ([]byte, []int) {
	return file_idl_likes_proto_rawDescGZIP(), []int{2}
}

func (x *DelLikesRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DelLikesRequest) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type DelLikesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DelLikesResponse) Reset() {
	*x = DelLikesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_likes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelLikesResponse) ProtoMessage() {}

func (x *DelLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_likes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelLikesResponse.ProtoReflect.Descriptor instead.
func (*DelLikesResponse) Descriptor() ([]byte, []int) {
	return file_idl_likes_proto_rawDescGZIP(), []int{3}
}

func (x *DelLikesResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DelLikesResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_idl_likes_proto protoreflect.FileDescriptor

var file_idl_likes_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x64, 0x6c, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4c,
	0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x69, 0x64, 0x22,
	0x3c, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x35, 0x0a,
	0x0f, 0x44, 0x65, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x70, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x32, 0x88, 0x01, 0x0a, 0x0c, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x12,
	0x16, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x6b, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x2e,
	0x41, 0x64, 0x64, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3b, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x6c,
	0x69, 0x6b, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c,
	0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3f, 0x5a,
	0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x49, 0x54, 0x75, 0x2d,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x57, 0x65, 0x47, 0x6f, 0x2f, 0x69, 0x74, 0x75, 0x5f, 0x72, 0x70,
	0x63, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e,
	0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_likes_proto_rawDescOnce sync.Once
	file_idl_likes_proto_rawDescData = file_idl_likes_proto_rawDesc
)

func file_idl_likes_proto_rawDescGZIP() []byte {
	file_idl_likes_proto_rawDescOnce.Do(func() {
		file_idl_likes_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_likes_proto_rawDescData)
	})
	return file_idl_likes_proto_rawDescData
}

var file_idl_likes_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_idl_likes_proto_goTypes = []interface{}{
	(*AddLikesRequest)(nil),  // 0: likes.AddLikesRequest
	(*AddLikesResponse)(nil), // 1: likes.AddLikesResponse
	(*DelLikesRequest)(nil),  // 2: likes.DelLikesRequest
	(*DelLikesResponse)(nil), // 3: likes.DelLikesResponse
}
var file_idl_likes_proto_depIdxs = []int32{
	0, // 0: likes.LikesService.AddLikes:input_type -> likes.AddLikesRequest
	2, // 1: likes.LikesService.DelLikes:input_type -> likes.DelLikesRequest
	1, // 2: likes.LikesService.AddLikes:output_type -> likes.AddLikesResponse
	3, // 3: likes.LikesService.DelLikes:output_type -> likes.DelLikesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_likes_proto_init() }
func file_idl_likes_proto_init() {
	if File_idl_likes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_likes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLikesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_likes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLikesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_likes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelLikesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_likes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelLikesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_likes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_likes_proto_goTypes,
		DependencyIndexes: file_idl_likes_proto_depIdxs,
		MessageInfos:      file_idl_likes_proto_msgTypes,
	}.Build()
	File_idl_likes_proto = out.File
	file_idl_likes_proto_rawDesc = nil
	file_idl_likes_proto_goTypes = nil
	file_idl_likes_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.12.3. DO NOT EDIT.

type LikesService interface {
	AddLikes(ctx context.Context, req *AddLikesRequest) (res *AddLikesResponse, err error)
	DelLikes(ctx context.Context, req *DelLikesRequest) (res *DelLikesResponse, err error)
}
